17-transform-to-and-from-arb
translate-agent/translate pull request #20
Opened 2023-02-13 16:26 UTC by VladislavsPerkanuks

2023-02-13 17:08 UTC, janishorsts requested changes

2023-02-13 17:08 UTC, janishorsts commented on pkg/convert/arb.go
> +		})
The following reduces code boilerplate by reducing the number of variables.

```suggestion
		msg  := messages.Message{ID: key}
		
		msg.Message, ok = value.(string)
		if !ok {
			return model.Messages{}, fmt.Errorf("unsupported value type '%T' for key '%s'", value, key)
		}

		msg.Description, err = findDescription(key)
		if err != nil {
			return model.Messages{}, fmt.Errorf("find description of '%s': %w", key, err)
		}

		messages.Messages = append(messages.Messages, msg)
```

2023-02-13 17:08 UTC, janishorsts commented on pkg/convert/arb.go
> +		if len(msg.Description) != 0 {
```suggestion
		// the intent is more precise with this one
		if len(msg.Description) > 0 {
		
		// or

		If msg.Description != "" {
```

2023-02-13 17:08 UTC, janishorsts commented on pkg/convert/arb_test.go
> +		wantErr bool
```suggestion
		wantErr error
```

2023-02-14 10:33 UTC, VladislavsPerkanuks commented on pkg/convert/arb.go
> +		keyMap, ok := subKey.(map[string]interface{})
I don't quite get what you meant here.
All information I got is from [flutter documentation](https://docs.flutter.dev/development/accessibility-and-localization/internationalization)

If I understand correctly, concrete type means that type has a full definition, which in this case is true. if there is a key for example **greeting** and there is metadata key \@greeting, which contains additional information for the message, such as Description, Placeholders, etc., then \@greeting has a defined structure, as mentioned in the comment
```json
"greeting": "Welcome {user}!",
"@greeting": {
  "description":"Used to greet specific user to website",
  "placeholders": {
    "user":{
      "type":"string",
      "example":"Bob"
      }
    }
  }
```

The metadata key can contain additional metadata keys, but **description** and **placeholders** are the most used ones.

2023-02-14 11:00 UTC, VladislavsPerkanuks commented on pkg/convert/arb.go
> +	dst := make(map[string]interface{}, len(messages.Messages)*2) //nolint:gomnd
Due to additional metadata keys, the map size is at least `len(messages.Messages)` and the max size of a map can be up to `len(messages.Messages)*2`.
It is better to allocate a max size beforehand, afaik

2023-02-14 14:42 UTC, merged