21-download-file
translate-agent/translate pull request #22
Opened 2023-02-15 10:38 UTC by VladislavsPerkanuks

2023-02-15 12:04 UTC, janishorsts requested changes

2023-02-15 12:04 UTC, janishorsts commented on pkg/translate/translate.go
> +		Language: LanguageData{Str: req.GetLanguage()},
There are at least two steps involved in processing a request:

- parse request (type/schema guard)
- validate request (logical guard)
- access control
- etc

If you separate these steps, it simplifies the flow and removes unnecessary temporary data (E.g. Language struct with Str and Tag fields) that leaks and generates noise.

```go
// one of the options is...

type uploadParams struct {
  Language language.Tag
  // ...
}

params, err := parseUploadParams(req *pb.UploadTranslationFileRequest) (*uploadParams, error)

// ...

if err := params.validate(); err != nil {
```

2023-02-15 12:46 UTC, VladislavsPerkanuks commented on pkg/translate/translate.go
> +type UploadParams struct {
Yeah, I wanted to do that but ran into problems when was making integration tests specifically for REST. My idea was to use the same `translate.UploadParams` to create table tests.
```go
	tests := []struct {
		name   string
		params translate.UploadParams
		want   uint
	}
```

What is the preferred solution then, if we make `uploadParams` inaccessible for integration tests? Creating custom struct for tests?

2023-02-15 13:23 UTC, janishorsts commented on pkg/translate/translate.go
> +type UploadParams struct {
yes, define a new struct in tests

2023-02-16 10:32 UTC, klavinsjanis approved these changes

2023-02-17 07:59 UTC, janishorsts commented on pkg/translate/translate.go
> +		return fmt.Errorf("'schema' must be specified")
```suggestion
		return fmt.Errorf("'schema' is required")
```

2023-02-17 08:07 UTC, janishorsts commented on pkg/translate/translate.go
> +		return nil, fmt.Errorf("parsing language '%s': %w", reqLanguage, err)
shorter, the verb in simple present form

```suggestion
		return nil, fmt.Errorf("parse language '%s': %w", reqLanguage, err)
```

2023-02-17 08:08 UTC, janishorsts approved these changes

2023-02-17 08:50 UTC, merged